import { Icon, IconBundle } from 'system/icons/IconBundle';

const icon = (ligature: string): Icon => ({
  className: 'material-icons-round',
  ligature,
});

export const SystemIcons: IconBundle = {
  linkUrl: 'https://fonts.googleapis.com/icon?family=Material+Icons+Round',
  icons: {
    logo: icon('alternate_email'),
    email: icon('email'),
    calendar: icon('calendar_today'),
    contacts: icon('contacts'),
    folder: icon('folder'),
    settings: icon('settings'),
    inbox: icon('inbox'),
    drafts: icon('drafts'),
    star: icon('star_outline'),
    sent: icon('send'),
    attachment: icon('attachment'),
    reply: icon('reply'),
    reply_all: icon('reply_all'),
    delete: icon('delete'),
    more: icon('more'),
    spam: icon('report'),
    label: icon('label'),
    search: icon('search'),
    add: icon('add_circle_outline'),
    remove: icon('remove'),
    logout: icon('logout'),
    preview: icon('preview'),
    download: icon('download'),
    important: icon('label_important'),
    bold: icon('format_bold'),
    italic: icon('format_italic'),
    strikethrough: icon('format_strikethrough'),
    code: icon('code'),
    link: icon('link'),
    align_left: icon('format_align_left'),
    align_right: icon('format_align_right'),
    align_center: icon('format_align_center'),
    align_justify: icon('format_align_justify'),
    numbered_list: icon('format_list_numbered'),
    bulleted_list: icon('format_list_bulleted'),
    quote: icon('format_quote'),
    image: icon('image'),
    video: icon('videocam'),
    error: icon('report'),
  },
};
