name: Publish Website

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Publish-Website:
    name: Publish-Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload the artifact
